import Head from "next/head";
import { useRouter } from "next/router";
import { createClient } from "next-sanity";
import PortableText from "react-portable-text";
import imageUrlBuilder from "@sanity/image-url";
import Link from "next/link";
const Post = ({ blog }) => {
  // use router to read the url and fetch the right blog
  const router = useRouter();
  const { slug } = router.query;
  const client = createClient({
    projectId: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID,
    dataset: process.env.NEXT_PUBLIC_SANITY_DATASET,
    useCdn: false,
  });
  const builder = imageUrlBuilder(client);

  const convertDate = new Date(blog.createdAt);

  return (
    <>
      <Head>
        <title>Arsh's Site | {blog.title}</title>
        <meta name="description" content="Generated by nest app" />
        <link rel="shortcut icon" href="/assets/secondIcon.svg" />
      </Head>
      <br />
      <br />
      <br />
      <br />
      <div className="flex items-center justify-center flex-col">
        <div className="mt-5 ">
          {/* <Image > */}
          <img
            src={blog.blogImage ? builder.image(blog.blogImage).url() : ""}
            className="object-fit h-40 md:h-60"
            alt=""
          />
        </div>
        <p className="uppercase text-sm tracking-widest text-gray-600 mt-1">
          {blog.blogImage.caption}
        </p>
        <div className="mt-4 uppercase text-xl md:text-3xl tracking-widest text-[#f76c6c]  text-center">
          {blog.title}
        </div>
        <div>
          <div className="mt-2 py-2 text-gray-600 text-xl w-[90vw] lg:w-[70vw] text-center">
            <PortableText
              // Pass in block content straight from Sanity.io
              content={blog.content}
              projectId="exkzudo9"
              dataset="production"
              // Optionally override marks, decorators, blocks, etc. in a flat
              // structure without doing any gymnastics
              serializers={{
                h1: (props) => <h1 style={{ color: "red" }} {...props} />,
                li: ({ children }) => (
                  <li className="special-list-item">{children}</li>
                ),
              }}
            />
          </div>
        </div>

        <div className="flex items-center mt-2">
          <img
            className="w-10 h-10 rounded-full mr-4 border-2"
            src="/assets/cartoon.png"
            alt="Avatar of a random"
          />
          <div className="text-sm">
            <p className="text-gray-900 leading-none">Arshdeep Singh</p>
            <p className="text-gray-600">
              {convertDate.getMonth() +
                "/" +
                convertDate.getDate() +
                "/" +
                convertDate.getFullYear()}
            </p>
          </div>
        </div>
      </div>


      <script
        dangerouslySetInnerHTML={{
          __html: `
document.querySelector("body").addEventListener("mousemove", eyeball)
function eyeball() {
  const eye = document.querySelectorAll(".eye");
  eye.forEach(function(eye) {
    let x = (eye.getBoundingClientRect().left) + (eye.clientWidth / 2);
    let y = (eye.getBoundingClientRect().top) + (eye.clientHeight / 2);
    let radian = Math.atan2(event.pageX - x, event.pageY - y);
    let rotation = (radian * (180 / Math.PI) * -1) + 270;
    eye.style.transform = "rotate("+rotation+"deg)"; 
  })
}
        `,
        }}
      />
    </>
  );
};

export default Post;

// implement SSR for fast loading
export async function getServerSideProps(context) {
  const { slug } = context.query;

  const client = createClient({
    projectId: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID,
    dataset: process.env.NEXT_PUBLIC_SANITY_DATASET,
    useCdn: false,
  });

  const query = `*[_type == "blog" && slug.current == '${slug}'][0]`;
  const blog = await client.fetch(query);
  return {
    props: {
      blog,
    },
  };
}
